version: "3.5"
services:
    db:
        image: mariadb:10.5.8
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: CHANGE_HERE
            MYSQL_USER: CHANGE_HERE
            MYSQL_PASSWORD: CHANGE_HERE
            MYSQL_DATABASE: CHANGE_HERE
        volumes:
            - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ./volumes/db/data:/var/lib/mysql
    api:
        build: ./api
        restart: always
        ports:
            - 8081:8081
            - 8086:8086
        environment:
            MYSQL_USER: CHANGE_HERE
            MYSQL_PASSWORD: CHANGE_HERE
            MYSQL_DATABASE: CHANGE_HERE
        depends_on:
            - db
    bot:
        build: ./bot
        restart: always
        ports:
            - 8083:8083
        depends_on:
            - db
            - api
    client:
        build: ./client
        restart: always
        ports:
            - 8080:8080
        volumes:
            - ./client/dist:/usr/share/nginx/html
        depends_on:
            - api
            - bot